remote_theme: zendesk/jekyll-theme-zendesk-garden@v0.7.3
title: Input Glyphs Documentation

version: false
auto_page_title: true
search_enabled: true

sidebar:
  - overview
  - getting-started
  - texture-map
  - custom-device
  - steamworks
  - label: Language-日本語
    children:
      - ja-overview
      - ja-getting-started
      - ja-texture-map
      - ja-custom-device
      - ja-steamworks
  - label: Language-中文
    children:
      - zh-CN-overview
      - zh-CN-getting-started
      - zh-CN-texture-map
      - zh-CN-custom-device
      - zh-CN-steamworks
